---
# generic DA3C configuration

algorithm:
  name: dqn                       # short name for algorithm to load

  input:
    shape: [4]                    # shape of input state
    history: 1                    # number of consecutive states to stack
    use_convolutions: false       # set to true to process input by convolution layers

  output:
    continuous: false             # set to true to switch to continuous action space
    action_size: 2                # action size for the given environment

  double_dqn: true

  hidden_sizes: [64]              # list of dense layers sizes, for ex. [128, 64]
  batch_size: 32                  # maximum batch size, which need to accumulate for one update

  max_global_step: 150000         # amount of maximum global steps to pass through the training
  start_sample_step: 2000
  update_target_interval: 2000

  rewards_gamma: 1.0              # rewards discount factor

  initial_learning_rate: 5e-4     # initial learning rate, which can be anneal by some procedure
  gradients_norm_clipping: false  # gradients clipping by global norm, if false then it is ignored
  optimizer: Adam                 # name of optimizer to use within training

  replay_buffer_size: 50000

  # greedy eps parameters
  initial_eps: 1.0
  end_eps: 0.02
  decay_steps: 10000
